[versions]
kotlin = "2.0.0-RC3"
compose = "1.6.10"
settings = "1.1.1"
dbus-java = "5.0.0"
koin = "3.6.0-wasm-alpha2"
voyager = "1.1.0-alpha04"
libres = "1.2.2"
ktlintPlugin = "12.1.1"
ktlint = "1.2.1"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:4.4.0"
dbus-java-core = { module = "com.github.hypfvieh:dbus-java-core", version.ref = "dbus-java" }
dbus-java-transport-native-unixsocket = { module = "com.github.hypfvieh:dbus-java-transport-native-unixsocket", version.ref = "dbus-java" }
tika-core = "org.apache.tika:tika-core:2.9.2"

# multiplatformsettings
settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-noarg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settings" }

windowSize = "dev.chrisbanes.material3:material3-window-size-class-multiplatform:0.5.0"
colorPicker = "com.godaddy.android.colorpicker:compose-color-picker:0.7.0"
materialKolor = "com.materialkolor:material-kolor:1.5.1"

kfswatch = { module = "io.github.irgaly.kfswatch:kfswatch", version = "1.0.0" }
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

libres-compose = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }

ktlint-rules-compose = { module = "io.nlopez.compose.rules:ktlint", version = "0.4.1" }

[bundles]
voyager = ["voyager-navigator", "voyager-tabNavigator", "voyager-transitions", "voyager-koin"]
koin = ["koin-compose", "koin-core"]
dbus-java = ["dbus-java-core", "dbus-java-transport-native-unixsocket"]
settings = ["settings", "settings-noarg"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
libres = { id = "io.github.skeptick.libres", version.ref = "libres" }

# Linters
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }