[versions]
kotlin = "1.9.0"
compose = "1.5.0-rc02"
multiplatformsettings = "1.0.0"
dbus-java = "4.3.0"
compose-icons = "1.1.0"
moko-resources = "0.23.0"

ktlint = "11.5.1"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:4.2.0"
dbus-java-core = { module = "com.github.hypfvieh:dbus-java-core", version.ref = "dbus-java" }
dbus-java-transport-native-unixsocket = { module = "com.github.hypfvieh:dbus-java-transport-native-unixsocket", version.ref = "dbus-java" }
tika-core = "org.apache.tika:tika-core:2.8.0"

# multiplatformsettings
settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformsettings" }
settings-noarg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformsettings" }

compose-icons = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "compose-icons" }

# moko-resources
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }

ktlint-rules-compose = { module = "io.nlopez.compose.rules:ktlint", version = "0.2.1" }

[bundles]
dbus-java = ["dbus-java-core", "dbus-java-transport-native-unixsocket"]
settings = ["settings", "settings-noarg"]
moko-resources = ["moko-resources", "moko-resources-compose"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }

# Linters
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }