[versions]
kotlin = "1.8.20"
compose = "1.4.1"
decompose = "2.0.0"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:3.5.4"
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }