name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - '.github/workflows/check.yml'
      - 'gradle/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - '.github/workflows/check.yml'
      - 'gradle/**'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build application packages
    strategy:
      matrix:
        runtime: [ linux-x64, win-x64 ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            shell: bash
            build: packageReleaseUberJarForCurrentOS packageReleaseDeb

          - runtime: win-x64
            arch: x64
            os: windows-latest
            shell: powershell
            build: packageReleaseUberJarForCurrentOS packageReleaseMsi

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JVM_DISTRIBUTION }}
          java-version: ${{ vars.JVM_VERSION }}
          architecture: ${{ matrix.arch }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew ${{ matrix.build }}

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-package-${{ matrix.runtime }}
          path: |
            tau/build/compose/binaries/main-release/
            tau/build/compose/jars/

      # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            tau/build/compose/logs/